apiVersion: v2
name: taynac
description: A Helm chart for taynac
type: application
version: 1.0.4
appVersion: 0.1.0-11-g503e5a7
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.23.0
