apiVersion: v2
name: taynac
description: A Helm chart for taynac
type: application
version: 2.0.4
appVersion: 1.0.0-7-ga250506
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.4
- name: nectarlib
  version: 3.2.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
