apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taynac.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
data:
  taynac.conf: |
{{ include "taynac-conf" . | indent 4 }}
